import BitcoinBase
import BitcoinCrypto
import Foundation

/// An affordance to sign multiple inputs of a bitcoin tx.
public struct TransactionSigner {

    /// Creates a new signer with default signature hash type of _all_.
    /// - Parameters:
    ///   - tx: A transaction to sign.
    ///   - prevouts: All previous outputs corresponding to each of the transaction's ins.
    public init(tx: Transaction, prevouts: [TransactionOutput]) {
        self.tx = tx
        hasher = .init(tx: tx, prevouts: prevouts, sighashType: .all)
    }

    /// Creates a new signer.
    /// - Parameters:
    ///   - tx: A transaction to sign.
    ///   - prevouts: All previous outputs corresponding to each of the transaction's ins.
    ///   - sighashType: An initial, optional signature hash type.
    public init(tx: Transaction, prevouts: [TransactionOutput], sighashType: SighashType? = Optional.none) {
        self.tx = tx
        hasher = .init(tx: tx, prevouts: prevouts, sighashType: sighashType)
    }

    /// The last version of the transaction containing all signatures generated by this signer.
    public private(set) var tx: Transaction

    public private(set) var lastSig: ExtendedSig?

    /// A hasher instance for generating the required signature hashes.
    private var hasher: SignatureHasher

    /// The current signature hash type.
    public var sighashType: SighashType? {
        get { hasher.sighashType }
        set { hasher.sighashType = newValue }
    }

    /// Signs a multi-signature input.
    /// - Parameters:
    ///   - input: A valid input index.
    ///   - redeemScript: An optional redeem script (pay-to-script-hash only).
    ///   - witnessScript: An optional witness script (pay-to-witness-script-hash only, also when wrapped).
    ///   - secretKeys: Secret keys for each signature.
    /// - Returns: A transaction with the signed input.
    @discardableResult
    public mutating func sign(input: Int, redeemScript: Script? = .none, witnessScript: Script? = .none, with secretKeys: [SecretKey]) -> Transaction {

        let sigVersion: SigVersion = if witnessScript != .none { .witnessV0 }
            else { .base }

        hasher.set(input: input, sigVersion: sigVersion, scriptCode: witnessScript?.binaryData ?? redeemScript?.binaryData)

        let lockScript = hasher.prevout.script

        precondition(
            // Bare multisig
            redeemScript == .none && witnessScript == .none && lockScript.isPayToMultisig ||

            // P2SH with multisig redeem script
            (redeemScript != .none && witnessScript == .none && lockScript == .payToScriptHash(redeemScript!) && redeemScript!.isPayToMultisig) ||

            // P2WSH with multisig witness script
            (redeemScript == .none && witnessScript != .none && lockScript == .payToWitnessScriptHash(witnessScript!) && witnessScript!.isPayToMultisig) ||

            // P2SH-P2WSH with multisig redeem script
            (/*redeemScript != .none && */ witnessScript != .none && lockScript == .payToScriptHash(.payToWitnessScriptHash(witnessScript!)) && witnessScript!.isPayToMultisig)
        )

        let sighash = hasher.value

        var sigs = [Data]()
        for secretKey in secretKeys {
            let sig = secretKey.sign(hash: sighash)
            let sigExt = ExtendedSig(sig, sighashType)
            sigs.append(sigExt.data)
            lastSig = sigExt
        }
        if let redeemScript { sigs.append(redeemScript.binaryData) }
        if let witnessScript { sigs.append(witnessScript.binaryData)}

        if let witnessScript {
            let witness = [Data()] + sigs
            tx.ins[input].witness = .init(witness)
            if lockScript.isPayToScriptHash {
                let redeemScriptP2WSH = Script.payToWitnessScriptHash(witnessScript)
                tx.ins[input].script = [.encodeMinimally(redeemScriptP2WSH.binaryData)]
            }
        } else {
            let unlockScript = Script([.zero] + sigs.map { Script.Operation.encodeMinimally($0) })
            tx.ins[input].script = unlockScript
        }
        return tx
    }

    /// Signs a single key input.
    /// - Parameters:
    ///   - input: A valid input index.
    ///   - secretKey: A secret key for signing.
    /// - Returns: A transaction with the signed input.
    @discardableResult
    public mutating func sign(input: Int, with secretKey: SecretKey) -> Transaction {
        let lockScript = hasher.prevouts[input].script

        let pubkeyHash = Data(Hash160.hash(data: secretKey.pubkey.data))
        let redeemScript = Script.payToWitnessPubkeyHash(pubkeyHash)

        precondition(
            lockScript.isPayToPubkey || lockScript.isPayToPubkeyHash || lockScript.isPayToWitnessKeyHash || lockScript.isPayToTaproot || (
                lockScript == .payToScriptHash(redeemScript)
        ))

        let sigVersion: SigVersion = if lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash { .witnessV0 }
                         else if lockScript.isPayToTaproot { .witnessV1 }
                         else { .base }

        let scriptCode: Data? = if lockScript.isPayToScriptHash {
            Script.segwitPKHScriptCode(pubkeyHash).binaryData
        } else { .none }

        hasher.set(input: input, sigVersion: sigVersion, scriptCode: scriptCode)
        let sighash = hasher.value

        let sig = if lockScript.isPayToTaproot {
            secretKey.taprootSecretKey().sign(hash: sighash, sigType: .schnorr)
        } else {
            secretKey.sign(hash: sighash)
        }

        let sigExt = ExtendedSig(sig, hasher.sighashType)
        lastSig = sigExt

        // For pay-to-public key we just need to sign the hash and add the signature to the input's unlock script.
        var witnessData = [sigExt.data]
        if lockScript.isPayToPubkeyHash || lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash {
            // For pay-to-public-key-hash we need to also add the public key to the unlock script.
            witnessData.append(secretKey.pubkey.data)
        }
        if lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash || lockScript.isPayToTaproot {
            // For pay-to-witness-public-key-hash we sign a different hash and we add the signature and public key to the input's _witness_.
            tx.ins[input].witness = .init(witnessData)
        }
        if lockScript.isPayToPubkey || lockScript.isPayToPubkeyHash {
            let ops = witnessData.map { Script.Operation.pushBytes($0) }
            tx.ins[input].script = .init(ops)
        }
        if lockScript.isPayToScriptHash {
            tx.ins[input].script = [.encodeMinimally(redeemScript.binaryData)]
        }
        return tx
    }
}
