import BitcoinBase
import BitcoinCrypto
import Foundation

/// An affordance to sign multiple inputs of a bitcoin tx.
public struct TransactionSigner {

    /// Creates a new signer with default signature hash type of _all_.
    /// - Parameters:
    ///   - tx: A transaction to sign.
    ///   - prevouts: All previous outputs corresponding to each of the transaction's ins.
    public init(tx: Transaction, prevouts: [TransactionOutput]) {
        self.tx = tx
        self.prevouts = prevouts
        self.sighashType = .all
    }

    /// Creates a new signer.
    /// - Parameters:
    ///   - tx: A transaction to sign.
    ///   - prevouts: All previous outputs corresponding to each of the transaction's ins.
    ///   - sighashType: An initial, optional signature hash type.
    public init(tx: Transaction, prevouts: [TransactionOutput], sighashType: SighashType?) {
        self.tx = tx
        self.prevouts = prevouts
        self.sighashType = sighashType
    }

    /// The last version of the transaction containing all signatures generated by this signer.
    public private(set) var tx: Transaction
    public private(set) var prevouts: [TransactionOutput]

    /// The current signature hash type.
    public var sighashType: SighashType?

    public private(set) var lastSig: ECDSASignature.Extended?

    /// Signs a multi-signature input.
    /// - Parameters:
    ///   - input: A valid input index.
    ///   - redeemScript: An optional redeem script (pay-to-script-hash only).
    ///   - witnessScript: An optional witness script (pay-to-witness-script-hash only, also when wrapped).
    ///   - secretKeys: Secret keys for each signature.
    /// - Returns: A transaction with the signed input.
    @discardableResult
    public mutating func sign(input: Int, redeemScript: Script? = nil, witnessScript: Script? = nil, with secretKeys: [SecretKey]) -> Transaction {

        guard let sighashType else { preconditionFailure() }

        let prevout = if prevouts.count == 1 { prevouts[0] } else { prevouts[input] }
        let lockScript = prevout.script

        precondition(
            // Bare multisig
            redeemScript == nil && witnessScript == nil && lockScript.isPayToMultisig ||

            // P2SH with multisig redeem script
            (redeemScript != nil && witnessScript == nil && lockScript == .payToScriptHash(redeemScript!) && redeemScript!.isPayToMultisig) ||

            // P2WSH with multisig witness script
            (redeemScript == nil && witnessScript != nil && lockScript == .payToWitnessScriptHash(witnessScript!) && witnessScript!.isPayToMultisig) ||

            // P2SH-P2WSH with multisig redeem script
            (/*redeemScript != nil && */ witnessScript != nil && lockScript == .payToScriptHash(.payToWitnessScriptHash(witnessScript!)) && witnessScript!.isPayToMultisig)
        )

        let sighash = if let witnessScript {
            SignatureHash.Segwit(tx: tx, input: input, sighashType: sighashType, scriptCode: witnessScript.binaryData, prevout: prevout).data
        } else if let redeemScript {
            SignatureHash(tx: tx, input: input, sighashType: sighashType, scriptCode: redeemScript.binaryData).data
        } else {
            SignatureHash(tx: tx, input: input, sighashType: sighashType, scriptCode: lockScript.binaryData).data
        }

        var sigs = [Data]()
        for secretKey in secretKeys {
            let sig = secretKey.sign(hash: sighash)
            let sigExt = ECDSASignature.Extended(sig, sighashType: sighashType)
            sigs.append(sigExt.data)
            lastSig = sigExt
        }
        if let redeemScript { sigs.append(redeemScript.binaryData) }
        if let witnessScript { sigs.append(witnessScript.binaryData)}

        if let witnessScript {
            let witness = [Data()] + sigs
            tx.ins[input].witness = .init(witness)
            if lockScript.isPayToScriptHash {
                let redeemScriptP2WSH = Script.payToWitnessScriptHash(witnessScript)
                tx.ins[input].script = [.encodeMinimally(redeemScriptP2WSH.binaryData)]
            }
        } else {
            let unlockScript = Script([.zero] + sigs.map { Script.Operation.encodeMinimally($0) })
            tx.ins[input].script = unlockScript
        }
        return tx
    }

    /// Signs a single key input.
    /// - Parameters:
    ///   - input: A valid input index.
    ///   - secretKey: A secret key for signing.
    /// - Returns: A transaction with the signed input.
    @discardableResult
    public mutating func sign(input: Int, with secretKey: SecretKey) -> Transaction {
        let lockScript = prevouts[input].script

        let pubkeyHash = Data(Hash160.hash(data: secretKey.pubkey.data))
        let redeemScript = Script.payToWitnessPubkeyHash(pubkeyHash)

        precondition(
            lockScript.isPayToPubkey ||
            lockScript.isPayToPubkeyHash ||
            lockScript.isPayToWitnessKeyHash ||
            lockScript == .payToScriptHash(redeemScript) ||
            lockScript.isPayToTaproot
        )

        let sighash: Data
        if lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash {
            // .witnessV0

            guard let sighashType else { preconditionFailure() }

            let scriptCode: Data? = if lockScript.isPayToWitnessKeyHash {
                nil
            } else { Script.segwitPKHScriptCode(pubkeyHash).binaryData }
            sighash = SignatureHash.Segwit(tx: tx, input: input, sighashType: sighashType, scriptCode: scriptCode, prevout: prevouts[input]).data
        } else if lockScript.isPayToTaproot {
            // .witnessV1
             sighash = SignatureHash.Taproot(tx: tx, input: input, sighashType: sighashType, prevouts: prevouts).data
        } else {
            guard let sighashType else { preconditionFailure() }
            // .base
            sighash = SignatureHash(tx: tx, input: input, sighashType: sighashType, scriptCode: lockScript.binaryData).data
        }

        let sigData: Data

        if lockScript.isPayToTaproot {
            let sig = secretKey.taprootSecretKey().signSchnorr(hash: sighash)
            sigData = SchnorrSignature.Extended(sig, sighashType: sighashType).data
        } else {
            guard let sighashType else { preconditionFailure() }

            let sig = secretKey.sign(hash: sighash)
            let sigExt = ECDSASignature.Extended(sig, sighashType: sighashType)
            lastSig = sigExt
            sigData = sigExt.data
        }

        // For pay-to-public key we just need to sign the hash and add the signature to the input's unlock script.
        var witnessData = [sigData]
        if lockScript.isPayToPubkeyHash || lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash {
            // For pay-to-public-key-hash we need to also add the public key to the unlock script.
            witnessData.append(secretKey.pubkey.data)
        }
        if lockScript.isPayToWitnessKeyHash || lockScript.isPayToScriptHash || lockScript.isPayToTaproot {
            // For pay-to-witness-public-key-hash we sign a different hash and we add the signature and public key to the input's _witness_.
            tx.ins[input].witness = .init(witnessData)
        }
        if lockScript.isPayToPubkey || lockScript.isPayToPubkeyHash {
            let ops = witnessData.map { Script.Operation.pushBytes($0) }
            tx.ins[input].script = .init(ops)
        }
        if lockScript.isPayToScriptHash {
            tx.ins[input].script = [.encodeMinimally(redeemScript.binaryData)]
        }
        return tx
    }
}
